backend:
  replicaCount: 4
  image:
    repository: deep-dive-devops-platform-app-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8000

frontend:
  replicaCount: 1
  image:
    repository: deep-dive-devops-platform-app-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80

ingress:
  enabled: false
  className: nginx
  host: deep-dive.local
  path: /
