apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "deep-dive-devops-platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
